[package]
edition = "2024"
name = "libsql_dart"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
hyper-rustls = { version = "0.25", features = ["webpki-roots"] }
libsql = "0.9.30"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
