// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/params.dart';
import '../utils/result.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'statement.dart';
import 'transaction.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InnerConnection>>
abstract class InnerConnection implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InnerDatabase>>
abstract class InnerDatabase implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibsqlConnection>>
abstract class LibsqlConnection implements RustOpaqueInterface {
  Future<void> batch({required String sql});

  Future<void> disableExtension();

  Future<void> enableExtension();

  Future<ExecuteResult> execute(
      {required String sql, LibsqlParams? parameters});

  Future<void> loadExtension({required String path, String? entryPoint});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LibsqlConnection> newInstance(
          {required InnerConnection connection,
          required InnerDatabase database}) =>
      RustLib.instance.api.crateApiConnectionLibsqlConnectionNew(
          connection: connection, database: database);

  Future<LibsqlStatement> prepare({required String sql});

  Future<QueryResult> query({required String sql, LibsqlParams? parameters});

  Future<void> sync_();

  Future<LibsqlTransaction> transaction({LibsqlTransactionBehavior? behavior});
}
