// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/parameters.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `DATABASE_REGISTRY`, `STATEMENT_REGISTRY`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

Future<ConnectResult> connect({required ConnectArgs args}) =>
    RustLib.instance.api.crateApiLibsqlConnect(args: args);

Future<SyncResult> sync({required SyncArgs args}) =>
    RustLib.instance.api.crateApiLibsqlSync(args: args);

Future<QueryResult> query({required QueryArgs args}) =>
    RustLib.instance.api.crateApiLibsqlQuery(args: args);

Future<ExecuteResult> execute({required ExecuteArgs args}) =>
    RustLib.instance.api.crateApiLibsqlExecute(args: args);

Future<PrepareResult> prepare({required PrepareArgs args}) =>
    RustLib.instance.api.crateApiLibsqlPrepare(args: args);

Future<void> close({required String dbId}) =>
    RustLib.instance.api.crateApiLibsqlClose(dbId: dbId);

Future<void> statementFinalize({required String statementId}) =>
    RustLib.instance.api
        .crateApiLibsqlStatementFinalize(statementId: statementId);

Future<void> statementReset({required String statementId}) =>
    RustLib.instance.api.crateApiLibsqlStatementReset(statementId: statementId);

Future<StatementQueryResult> statementQuery(
        {required StatementQueryArgs args}) =>
    RustLib.instance.api.crateApiLibsqlStatementQuery(args: args);

Future<StatementExecuteResult> statementExecute(
        {required StatementExecuteArgs args}) =>
    RustLib.instance.api.crateApiLibsqlStatementExecute(args: args);

Future<BatchResult> batch({required BatchArgs args}) =>
    RustLib.instance.api.crateApiLibsqlBatch(args: args);

class BatchArgs {
  final String dbId;
  final String sql;

  const BatchArgs({
    required this.dbId,
    required this.sql,
  });

  @override
  int get hashCode => dbId.hashCode ^ sql.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchArgs &&
          runtimeType == other.runtimeType &&
          dbId == other.dbId &&
          sql == other.sql;
}

class BatchResult {
  final String? errorMessage;

  const BatchResult({
    this.errorMessage,
  });

  @override
  int get hashCode => errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchResult &&
          runtimeType == other.runtimeType &&
          errorMessage == other.errorMessage;
}

class ConnectArgs {
  final String url;
  final String? authToken;
  final String? syncUrl;
  final BigInt? syncIntervalSeconds;
  final String? encryptionKey;
  final bool? readYourWrites;
  final LibsqlOpenFlags? openFlags;

  const ConnectArgs({
    required this.url,
    this.authToken,
    this.syncUrl,
    this.syncIntervalSeconds,
    this.encryptionKey,
    this.readYourWrites,
    this.openFlags,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      authToken.hashCode ^
      syncUrl.hashCode ^
      syncIntervalSeconds.hashCode ^
      encryptionKey.hashCode ^
      readYourWrites.hashCode ^
      openFlags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectArgs &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          authToken == other.authToken &&
          syncUrl == other.syncUrl &&
          syncIntervalSeconds == other.syncIntervalSeconds &&
          encryptionKey == other.encryptionKey &&
          readYourWrites == other.readYourWrites &&
          openFlags == other.openFlags;
}

class ConnectResult {
  final String? errorMessage;
  final String? dbId;

  const ConnectResult({
    this.errorMessage,
    this.dbId,
  });

  @override
  int get hashCode => errorMessage.hashCode ^ dbId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectResult &&
          runtimeType == other.runtimeType &&
          errorMessage == other.errorMessage &&
          dbId == other.dbId;
}

class ExecuteArgs {
  final String dbId;
  final String sql;
  final Parameters? parameters;

  const ExecuteArgs({
    required this.dbId,
    required this.sql,
    this.parameters,
  });

  @override
  int get hashCode => dbId.hashCode ^ sql.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecuteArgs &&
          runtimeType == other.runtimeType &&
          dbId == other.dbId &&
          sql == other.sql &&
          parameters == other.parameters;
}

class ExecuteResult {
  final BigInt rowsAffected;
  final String? errorMessage;

  const ExecuteResult({
    required this.rowsAffected,
    this.errorMessage,
  });

  @override
  int get hashCode => rowsAffected.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecuteResult &&
          runtimeType == other.runtimeType &&
          rowsAffected == other.rowsAffected &&
          errorMessage == other.errorMessage;
}

enum LibsqlOpenFlags {
  readOnly,
  readWrite,
  create,
  ;
}

class PrepareArgs {
  final String dbId;
  final String sql;

  const PrepareArgs({
    required this.dbId,
    required this.sql,
  });

  @override
  int get hashCode => dbId.hashCode ^ sql.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareArgs &&
          runtimeType == other.runtimeType &&
          dbId == other.dbId &&
          sql == other.sql;
}

class PrepareResult {
  final String? statementId;
  final String? errorMessage;

  const PrepareResult({
    this.statementId,
    this.errorMessage,
  });

  @override
  int get hashCode => statementId.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareResult &&
          runtimeType == other.runtimeType &&
          statementId == other.statementId &&
          errorMessage == other.errorMessage;
}

class QueryArgs {
  final String dbId;
  final String sql;
  final Parameters? parameters;

  const QueryArgs({
    required this.dbId,
    required this.sql,
    this.parameters,
  });

  @override
  int get hashCode => dbId.hashCode ^ sql.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryArgs &&
          runtimeType == other.runtimeType &&
          dbId == other.dbId &&
          sql == other.sql &&
          parameters == other.parameters;
}

class QueryResult {
  final List<Map<String, ReturnValue>> rows;
  final BigInt rowsAffected;
  final PlatformInt64 lastInsertRowid;
  final String? errorMessage;

  const QueryResult({
    required this.rows,
    required this.rowsAffected,
    required this.lastInsertRowid,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      rowsAffected.hashCode ^
      lastInsertRowid.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryResult &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          rowsAffected == other.rowsAffected &&
          lastInsertRowid == other.lastInsertRowid &&
          errorMessage == other.errorMessage;
}

class StatementExecuteArgs {
  final String statementId;
  final Parameters? parameters;

  const StatementExecuteArgs({
    required this.statementId,
    this.parameters,
  });

  @override
  int get hashCode => statementId.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementExecuteArgs &&
          runtimeType == other.runtimeType &&
          statementId == other.statementId &&
          parameters == other.parameters;
}

class StatementExecuteResult {
  final BigInt rowsAffected;
  final String? errorMessage;

  const StatementExecuteResult({
    required this.rowsAffected,
    this.errorMessage,
  });

  @override
  int get hashCode => rowsAffected.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementExecuteResult &&
          runtimeType == other.runtimeType &&
          rowsAffected == other.rowsAffected &&
          errorMessage == other.errorMessage;
}

class StatementQueryArgs {
  final String statementId;
  final Parameters? parameters;

  const StatementQueryArgs({
    required this.statementId,
    this.parameters,
  });

  @override
  int get hashCode => statementId.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementQueryArgs &&
          runtimeType == other.runtimeType &&
          statementId == other.statementId &&
          parameters == other.parameters;
}

class StatementQueryResult {
  final List<Map<String, ReturnValue>> rows;
  final BigInt rowsAffected;
  final PlatformInt64 lastInsertRowid;
  final String? errorMessage;

  const StatementQueryResult({
    required this.rows,
    required this.rowsAffected,
    required this.lastInsertRowid,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      rowsAffected.hashCode ^
      lastInsertRowid.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementQueryResult &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          rowsAffected == other.rowsAffected &&
          lastInsertRowid == other.lastInsertRowid &&
          errorMessage == other.errorMessage;
}

class SyncArgs {
  final String dbId;

  const SyncArgs({
    required this.dbId,
  });

  @override
  int get hashCode => dbId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncArgs &&
          runtimeType == other.runtimeType &&
          dbId == other.dbId;
}

class SyncResult {
  final String? errorMessage;

  const SyncResult({
    this.errorMessage,
  });

  @override
  int get hashCode => errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          errorMessage == other.errorMessage;
}
