// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/params.dart';
import '../utils/result.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InnerStatement>>
abstract class InnerStatement implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibsqlStatement>>
abstract class LibsqlStatement implements RustOpaqueInterface {
  Future<ExecuteResult> execute({LibsqlParams? parameters});

  Future<void> finalize();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LibsqlStatement> newInstance(
          {required InnerStatement statement}) =>
      RustLib.instance.api
          .crateApiStatementLibsqlStatementNew(statement: statement);

  Future<QueryResult> query({LibsqlParams? parameters});

  Future<void> reset();
}
