// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'parameters.freezed.dart';

@freezed
sealed class ParamValue with _$ParamValue {
  const ParamValue._();

  const factory ParamValue.integer(
    PlatformInt64 field0,
  ) = ParamValue_Integer;
  const factory ParamValue.real(
    double field0,
  ) = ParamValue_Real;
  const factory ParamValue.text(
    String field0,
  ) = ParamValue_Text;
  const factory ParamValue.blob(
    Uint8List field0,
  ) = ParamValue_Blob;
  const factory ParamValue.null_() = ParamValue_Null;
}

class Parameters {
  final List<ParamValue>? positional;
  final Map<String, ParamValue>? named;

  const Parameters({
    this.positional,
    this.named,
  });

  @override
  int get hashCode => positional.hashCode ^ named.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Parameters &&
          runtimeType == other.runtimeType &&
          positional == other.positional &&
          named == other.named;
}
