// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'params.freezed.dart';

class LibsqlParams {
  final List<LibsqlValue>? positional;
  final Map<String, LibsqlValue>? named;

  const LibsqlParams({
    this.positional,
    this.named,
  });

  @override
  int get hashCode => positional.hashCode ^ named.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibsqlParams &&
          runtimeType == other.runtimeType &&
          positional == other.positional &&
          named == other.named;
}

@freezed
sealed class LibsqlValue with _$LibsqlValue {
  const LibsqlValue._();

  const factory LibsqlValue.integer(
    PlatformInt64 field0,
  ) = LibsqlValue_Integer;
  const factory LibsqlValue.real(
    double field0,
  ) = LibsqlValue_Real;
  const factory LibsqlValue.text(
    String field0,
  ) = LibsqlValue_Text;
  const factory LibsqlValue.blob(
    Uint8List field0,
  ) = LibsqlValue_Blob;
  const factory LibsqlValue.null_() = LibsqlValue_Null;
}
