// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'return_value.freezed.dart';

@freezed
sealed class LibsqlReturnValue with _$LibsqlReturnValue {
  const LibsqlReturnValue._();

  const factory LibsqlReturnValue.integer(
    PlatformInt64 field0,
  ) = LibsqlReturnValue_Integer;
  const factory LibsqlReturnValue.real(
    double field0,
  ) = LibsqlReturnValue_Real;
  const factory LibsqlReturnValue.text(
    String field0,
  ) = LibsqlReturnValue_Text;
  const factory LibsqlReturnValue.blob(
    Uint8List field0,
  ) = LibsqlReturnValue_Blob;
  const factory LibsqlReturnValue.null_() = LibsqlReturnValue_Null;
}
