// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'return_value.freezed.dart';

@freezed
sealed class ReturnValue with _$ReturnValue {
  const ReturnValue._();

  const factory ReturnValue.integer(
    PlatformInt64 field0,
  ) = ReturnValue_Integer;
  const factory ReturnValue.real(
    double field0,
  ) = ReturnValue_Real;
  const factory ReturnValue.text(
    String field0,
  ) = ReturnValue_Text;
  const factory ReturnValue.blob(
    Uint8List field0,
  ) = ReturnValue_Blob;
  const factory ReturnValue.null_() = ReturnValue_Null;
}
