name: Publish
on:
  push:
    tags:
      - 'v*'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
      - uses: flutter-actions/setup-flutter@v4
      - name: Install dependencies
        run: dart pub get
      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen
      - name: Run flutter_rust_bridge_codegen
        run: flutter_rust_bridge_codegen generate
      - name: Publish
        run: dart pub publish --force
